import { readFile, writeFile, mkdir, rename, access } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const AVAILABLE=new Set(["available","low_stock","sold_out","temporarily_unavailable","preorder","discontinued","unknown","mapping_error","suspended"]);
const BLOCKED=new Set(["sold_out","suspended","discontinued","mapping_error","unknown"]);
const PROVIDERS=new Set(["manual","printify","printful","gelato","gooten"]);
const secretPattern=/(secret|password|token|api[_-]?key|private[_-]?key|client[_-]?secret)/i;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const stable=v=>JSON.stringify(canonical(v));
export const desiredHash=value=>createHash("sha256").update(stable(value)).digest("hex");
export const idempotencyKey=({merchant,revision,product="catalog",variant="none",operation,data})=>`nume:${merchant}:${revision}:${product}:${variant}:${operation}:${desiredHash(data).slice(0,24)}`;
export const checkoutEligible=status=>!BLOCKED.has(status);
export async function loadJson(file){return JSON.parse(await readFile(file,"utf8"));}
const issue=(errors,file,pid,vid,field,message)=>errors.push(`${file}: product=${pid||"-"} variant=${vid||"-"} field=${field}: ${message}`);
export async function validateVendorCatalog(catalog,{file="catalog",connection}={}){
 const errors=[],warnings=[]; if(!catalog||typeof catalog!=="object") return {valid:false,errors:[`${file}: catalog must be an object`],warnings};
 for(const key of ["schema_version","catalog_id","merchant_id","storefront_id","assigned_row_ids","currency","revision","updated_at","products","extensions"]) if(!(key in catalog)) issue(errors,file,null,null,key,"required field is missing");
 if(catalog.schema_version!=="1.0.0") issue(errors,file,null,null,"schema_version","unsupported schema version");
 if(!/^[a-z]{3}$/.test(catalog.currency||"")) issue(errors,file,null,null,"currency","invalid ISO-style lowercase currency");
 if(!Number.isInteger(catalog.revision)||catalog.revision<1) issue(errors,file,null,null,"revision","must be a positive integer");
 let ownership={};try{ownership=(await loadJson(path.join(ROOT,"data/catalog-sync/row-ownership.json"))).rows}catch{}
 const assigned=new Set(catalog.assigned_row_ids||[]); for(const row of assigned){if(!ownership[row]) issue(errors,file,null,null,"assigned_row_ids",`unknown row ${row}`);else if(ownership[row]!==catalog.merchant_id) issue(errors,file,null,null,"assigned_row_ids",`unauthorized row ${row}`);}
 if(connection&&connection.merchant_id!==catalog.merchant_id) issue(errors,file,null,null,"merchant_id","connection belongs to another merchant");
 const pids=new Set(),vids=new Set(),skus=new Set();
 for(const p of catalog.products||[]){const pid=p.product_id;if(pids.has(pid))issue(errors,file,pid,null,"product_id","duplicate product ID");pids.add(pid);
  if(p.storefront_id!==catalog.storefront_id)issue(errors,file,pid,null,"storefront_id","does not match catalog storefront"); if(!p.title?.trim())issue(errors,file,pid,null,"title","missing title");if(!p.description?.trim())issue(errors,file,pid,null,"description","missing description");if(!p.variants?.length)issue(errors,file,pid,null,"variants","at least one variant is required");
  for(const row of p.row_ids||[]){if(!assigned.has(row))issue(errors,file,pid,null,"row_ids",`row ${row} is not assigned to this catalog`);if(ownership[row]!==catalog.merchant_id)issue(errors,file,pid,null,"row_ids",`unauthorized row ${row}`);}
  for(const m of p.media||[]){if(m.kind==="public_https"||m.kind==="provider"){try{const u=new URL(m.url);if(u.protocol!=="https:")throw 0}catch{issue(errors,file,pid,null,"media.url",`unsafe public image URL ${m.url}`)}}else if(m.kind==="local"){const local=path.join(ROOT,"public",String(m.url).replace(/^\//,""));try{await access(local)}catch{issue(errors,file,pid,null,"media.url",`unavailable local image ${m.url}`)}}else if(m.kind==="managed") warnings.push(`${file}: product=${pid} field=media: managed upload awaiting publication`);else issue(errors,file,pid,null,"media.kind","invalid media kind");}
  for(const ref of p.external_references||[])checkRef(ref,pid,null); for(const v of p.variants||[]){if(vids.has(v.variant_id))issue(errors,file,pid,v.variant_id,"variant_id","duplicate variant ID");vids.add(v.variant_id);if(skus.has(v.sku))issue(errors,file,pid,v.variant_id,"sku","duplicate merchant SKU");skus.add(v.sku);
   if(!v.title?.trim())issue(errors,file,pid,v.variant_id,"title","missing title");if(!Number.isInteger(v.retail_price?.amount_minor)||v.retail_price.amount_minor<0)issue(errors,file,pid,v.variant_id,"retail_price.amount_minor","must be a non-negative integer; floating-point money is forbidden");if(v.currency!==catalog.currency||v.retail_price?.currency!==catalog.currency)issue(errors,file,pid,v.variant_id,"currency","must match catalog currency");if(!AVAILABLE.has(v.availability?.status))issue(errors,file,pid,v.variant_id,"availability.status","invalid availability state");if(v.fulfillment_mapping&&!PROVIDERS.has(v.fulfillment_mapping.provider))issue(errors,file,pid,v.variant_id,"fulfillment_mapping.provider","unknown provider mapping");for(const ref of v.external_references||[])checkRef(ref,pid,v.variant_id);
  }}
 function checkRef(ref,pid,vid){if(!ref||typeof ref.system!=="string"||typeof ref.id!=="string"||!ref.id)issue(errors,file,pid,vid,"external_references","malformed external reference");if(ref?.system?.startsWith("stripe_")&&connection&&ref.account_id&&ref.account_id!==connection.stripe_account_id)issue(errors,file,pid,vid,"external_references.account_id","Stripe reference belongs to another connected account");const active=(vid?catalog.products.find(x=>x.product_id===pid)?.variants.find(x=>x.variant_id===vid)?.external_references:[])?.filter?.(x=>x.system==="stripe_price"&&x.active);if(active?.length>1)issue(errors,file,pid,vid,"external_references","conflicting active Price references");}
 const scan=(o,p="")=>{if(!o||typeof o!=="object")return;for(const [k,v]of Object.entries(o)){if(secretPattern.test(k))issue(errors,file,null,null,p?`${p}.${k}`:k,"embedded credentials are forbidden");if(typeof v==="object")scan(v,p?`${p}.${k}`:k)}};scan(catalog);
 return {valid:errors.length===0,errors,warnings};
}
export function normalizeCatalog(c){return {...c,assigned_row_ids:[...c.assigned_row_ids].sort(),products:[...c.products].map(p=>({...p,row_ids:[...p.row_ids],media:[...p.media].sort((a,b)=>a.sort_order-b.sort_order),variants:[...p.variants]}))};}
export function buildPlan(desired,previous=null){const old=new Map((previous?.products||[]).map(p=>[p.product_id,p])),plan={products_to_create:[],products_to_update:[],products_unchanged:[],products_removed:[],prices_to_create:[],previous_prices_to_deactivate:[],availability_changes:[],media_changes:[],row_placement_changes:[],warnings:[],blocking_errors:[]};
 for(const p of desired.products){const before=old.get(p.product_id);if(!before)plan.products_to_create.push(p.product_id);else{const mutable=x=>({title:x.title,description:x.description,active:x.active,status:x.status});if(stable(mutable(p))!==stable(mutable(before)))plan.products_to_update.push(p.product_id);else plan.products_unchanged.push(p.product_id);if(stable(p.media)!==stable(before.media))plan.media_changes.push(p.product_id);if(stable(p.row_ids)!==stable(before.row_ids))plan.row_placement_changes.push(p.product_id)} const oldv=new Map((before?.variants||[]).map(v=>[v.variant_id,v]));for(const v of p.variants){const ov=oldv.get(v.variant_id);if(!ov||stable(v.retail_price)!==stable(ov.retail_price)){plan.prices_to_create.push(v.variant_id);if(ov)plan.previous_prices_to_deactivate.push(v.variant_id)}if(ov&&ov.availability.status!==v.availability.status)plan.availability_changes.push({variant_id:v.variant_id,from:ov.availability.status,to:v.availability.status})}old.delete(p.product_id)}plan.products_removed=[...old.keys()];if(plan.products_removed.length)plan.warnings.push("Removed products stay in Stripe and are omitted from the confirmed website snapshot; use --archive-removed to deactivate Stripe records.");return plan;}
export class StripeRestClient{constructor(secret,account){this.secret=secret;this.account=account}async request(method,endpoint,body,key){const params=new URLSearchParams();for(const[k,v]of Object.entries(body||{}))if(v!==undefined&&v!==null){if(typeof v==="object")for(const[a,b]of Object.entries(v))params.set(`${k}[${a}]`,String(b));else params.set(k,String(v));}const r=await fetch(`https://api.stripe.com/v1/${endpoint}`,{method,headers:{Authorization:`Bearer ${this.secret}`,"Stripe-Account":this.account,"Idempotency-Key":key,"Content-Type":"application/x-www-form-urlencoded"},body:params});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||`Stripe ${r.status}`);return j}createProduct(b,k){return this.request("POST","products",b,k)}updateProduct(id,b,k){return this.request("POST",`products/${id}`,b,k)}createPrice(b,k){return this.request("POST","prices",b,k)}deactivatePrice(id,k){return this.request("POST",`prices/${id}`,{active:false},k)}}
export class MockStripeClient{constructor(state={products:{},prices:{}}){this.state=state}async createProduct(b,k){return this.state.products[k]??= {id:`prod_mock_${desiredHash(k).slice(0,12)}`,...b}}async updateProduct(id,b){return {id,...b}}async createPrice(b,k){return this.state.prices[k]??={id:`price_mock_${desiredHash(k).slice(0,12)}`,...b}}async deactivatePrice(id){return{id,active:false}}}
async function connectionFor(merchant){const all=await loadJson(path.join(ROOT,"data/catalog-sync/merchant-connections.json"));return all.connections.find(x=>x.merchant_id===merchant)}
export async function catalogPathFor(merchant){return path.join(ROOT,"data/vendor-catalogs",`${merchant}.json`)}
export async function statusFor(merchant){try{return await loadJson(path.join(ROOT,"data/catalog-sync/state",`${merchant}.json`))}catch{return {merchant_id:merchant,last_result:"never synchronized",published_revision:null,last_synchronized_at:null}}}

async function publishMarketplace(catalog){
 const catalogFile=path.join(ROOT,"data/catalog-sync/published-marketplace.v1.json"),layoutFile=path.join(ROOT,"data/catalog-sync/published-layout.v1.json");
 const market=await loadJson(catalogFile),layout=await loadJson(layoutFile),owned=new Set(catalog.assigned_row_ids);
 market.products=[...market.products.filter(p=>p.storefront_id!==catalog.storefront_id),...catalog.products];market.generated_at=new Date().toISOString();
 for(const row of layout.rows)if(owned.has(row.row_id))row.product_ids=catalog.products.filter(p=>p.active&&p.status==="active"&&p.row_ids.includes(row.row_id)).map(p=>p.product_id);
 await writeFile(`${catalogFile}.tmp`,JSON.stringify(market,null,2));await writeFile(`${layoutFile}.tmp`,JSON.stringify(layout,null,2));await rename(`${catalogFile}.tmp`,catalogFile);await rename(`${layoutFile}.tmp`,layoutFile);
}
export async function synchronizeCatalog({catalogPath,merchant,dryRun=false,confirm=false,stripeClient,publisher,archiveRemoved=false,failPublication=false}={}){const file=catalogPath||await catalogPathFor(merchant);const draft=await loadJson(file);merchant=merchant||draft.merchant_id;if(merchant!==draft.merchant_id){const e=new Error("merchant argument does not own catalog");e.exitCode=3;throw e}const connection=await connectionFor(merchant);if(!connection||connection.status==="disabled"){const e=new Error("merchant has no authorized Stripe connection");e.exitCode=3;throw e}const validation=await validateVendorCatalog(draft,{file,connection});if(!validation.valid){const e=new Error(validation.errors.join("\n"));e.validation=validation;e.exitCode=1;throw e}const normalized=normalizeCatalog(draft);const state=await statusFor(merchant);let previous=null;try{previous=await loadJson(state.desired_catalog_path)}catch{}const plan=buildPlan(normalized,previous);plan.warnings.push(...validation.warnings);if(dryRun||!confirm)return{phase:"planned",catalog:normalized,plan,validation,state};
 const lock=path.join(ROOT,"data/catalog-sync/state",`${merchant}.lock`);await mkdir(path.dirname(lock),{recursive:true});try{await writeFile(lock,String(process.pid),{flag:"wx"})}catch{const e=new Error("catalog update already in progress for merchant");e.exitCode=1;throw e}
 try{let refs=state.stripe_references||{};const client=stripeClient||(process.env.NUME_STRIPE_SECRET_KEY?new StripeRestClient(process.env.NUME_STRIPE_SECRET_KEY,connection.stripe_account_id):process.env.NUME_VCATALOG_ALLOW_MOCK_STRIPE==="1"?new MockStripeClient(state.mock_stripe_state):null);if(!client){const e=new Error("Stripe server credential is unavailable");e.exitCode=3;throw e}
  try{for(const p of normalized.products){let productId=refs[p.product_id]?.product_id;const publicImages=p.media.filter(m=>(m.kind==="public_https"||m.kind==="provider")&&m.url.startsWith("https://")).map(m=>m.url);const availability=p.variants.map(v=>v.availability.status).join(",");const meta={nume_product_id:p.product_id,nume_merchant_id:merchant,nume_availability:availability};const key=idempotencyKey({merchant,revision:draft.revision,product:p.product_id,operation:productId?"update_product":"create_product",data:{title:p.title,description:p.description,publicImages,meta}});const sp=productId?await client.updateProduct(productId,{name:p.title,description:p.description,images:publicImages,metadata:meta,active:p.active},key):await client.createProduct({name:p.title,description:p.description,images:publicImages,metadata:meta,active:p.active},key);productId=sp.id;refs[p.product_id]??={product_id:productId,variants:{}};refs[p.product_id].product_id=productId;
   for(const v of p.variants){const prior=refs[p.product_id].variants[v.variant_id];if(!prior||prior.amount_minor!==v.retail_price.amount_minor||prior.currency!==v.currency){const metadata={nume_variant_id:v.variant_id,nume_product_id:p.product_id,nume_merchant_id:merchant,nume_availability:v.availability.status,...(Number.isInteger(v.availability.quantity)?{nume_quantity:String(v.availability.quantity)}:{})};const pk=idempotencyKey({merchant,revision:draft.revision,product:p.product_id,variant:v.variant_id,operation:"create_price",data:{amount:v.retail_price,metadata}});const price=await client.createPrice({product:productId,unit_amount:v.retail_price.amount_minor,currency:v.currency,metadata},pk);if(prior?.price_id){await client.deactivatePrice(prior.price_id,idempotencyKey({merchant,revision:draft.revision,product:p.product_id,variant:v.variant_id,operation:"deactivate_price",data:{id:prior.price_id}}));}refs[p.product_id].variants[v.variant_id]={price_id:price.id,amount_minor:v.retail_price.amount_minor,currency:v.currency,historical_price_ids:[...(prior?.historical_price_ids||[]),...(prior?.price_id?[prior.price_id]:[])]};}}
  }}catch(error){await writeFile(path.join(ROOT,"data/catalog-sync/state",`${merchant}.json`),JSON.stringify({...state,merchant_id:merchant,last_result:"stripe_failed",error:String(error.message)},null,2));throw error}
  const hash=desiredHash(normalized),snapDir=path.join(ROOT,"data/catalog-sync/snapshots",merchant),snapshot=path.join(snapDir,`${draft.revision}-${hash.slice(0,16)}.json`),active=path.join(snapDir,"active.json");await mkdir(snapDir,{recursive:true});const snapshotBody={...normalized,published_at:new Date().toISOString(),stripe_references:refs};try{if(failPublication)throw new Error("injected publication failure");await writeFile(`${snapshot}.tmp`,JSON.stringify(snapshotBody,null,2));await rename(`${snapshot}.tmp`,snapshot);if(publisher)await publisher(snapshotBody);else await publishMarketplace(normalized);await writeFile(`${active}.tmp`,JSON.stringify({snapshot_path:snapshot,revision:draft.revision,hash},null,2));await rename(`${active}.tmp`,active)}catch(error){const partial={...state,merchant_id:merchant,last_result:"partial_stripe_applied",recoverable:true,stripe_references:refs,pending_snapshot:{revision:draft.revision,hash},mock_stripe_state:client.state};await writeFile(path.join(ROOT,"data/catalog-sync/state",`${merchant}.json`),JSON.stringify(partial,null,2));const e=new Error(`Stripe applied; publication can be retried: ${error.message}`);e.exitCode=4;throw e}
  const audit={event:"vendor_catalog_synchronized",merchant_id:merchant,catalog_id:draft.catalog_id,revision:draft.revision,hash,at:new Date().toISOString(),stripe_account_id:connection.stripe_account_id,archived_removed:Boolean(archiveRemoved)};await mkdir(path.join(ROOT,"data/catalog-sync/audit"),{recursive:true});await writeFile(path.join(ROOT,"data/catalog-sync/audit",`${Date.now()}-${merchant}.json`),JSON.stringify(audit,null,2));const next={merchant_id:merchant,published_revision:draft.revision,last_synchronized_at:audit.at,last_result:"success",snapshot_path:snapshot,desired_catalog_path:file,stripe_references:refs,mock_stripe_state:client.state};await writeFile(path.join(ROOT,"data/catalog-sync/state",`${merchant}.json`),JSON.stringify(next,null,2));return{phase:"complete",plan,audit,state:next};
 }finally{const{unlink}=await import("node:fs/promises");await unlink(lock).catch(()=>{})}}
